/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import db.dao.DAOEmpleados;
import db.dao.DAOManager;
import db.dao.DAOProductos;
import db.dao.DAOProveedores;
import java.awt.Color;
import model.tm.TMProducto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Administrador;
import model.Empleado;
import model.Producto;
import model.Proveedor;
import model.tm.TMEmpleado;
import model.tm.TMProveedore;

/**
 *
 * @author sega_
 */
public class MantenedorAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorApoderado
     */
    private DAOManager manager;
    private int desiredWidth = 200;
    //private MantenedorInicio oInicio;

    public MantenedorAdministrador() throws SQLException {
        initComponents();
        empleado_txt_id.setEditable(false);
        empleado_txt_id.setEnabled(false);
        this.setLocationRelativeTo(null);
        try {

            this.manager = new DAOManager();
            actualizarTablaEmpleados("");
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Enciende el Xamppo agrega la libreria", "Aceptar", JOptionPane.DEFAULT_OPTION);
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleado_tabbed = new javax.swing.JTabbedPane();
        tbb_empleado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        empleado_pnl_form = new javax.swing.JPanel();
        empleado_txt_nombre = new javax.swing.JTextField();
        empleado_txt_rut = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empleado_txt_cargo = new javax.swing.JTextField();
        empleado_cbo_nivelAcceso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empleado_txt_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        empleado_btn_elliminar = new javax.swing.JButton();
        empleado_btn_registrar = new javax.swing.JButton();
        empleado_btn_actualizar = new javax.swing.JButton();
        empleado_txt_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleado_tbl = new javax.swing.JTable();
        tbb_proveedores = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        proveedor_pnl_form = new javax.swing.JPanel();
        proveedor_txt_nombre = new javax.swing.JTextField();
        proveedor_txt_rut = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        proveedor_txt_correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        proveedor_txt_id = new javax.swing.JTextField();
        proveedor_txt_telefono = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        proveedor_btn_elliminar = new javax.swing.JButton();
        proveedor_btn_registrar = new javax.swing.JButton();
        proveedor_btn_actualizar = new javax.swing.JButton();
        proveedor_txt_buscar = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        proveedor_tbl = new javax.swing.JTable();
        tbb_productos = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        empleado_pnl_form2 = new javax.swing.JPanel();
        producto_txt_nombre = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        producto_txt_precio = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        producto_txt_id = new javax.swing.JTextField();
        producto_txt_cantidad = new javax.swing.JTextField();
        producto_txt_descripcion = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        producto_btn_elliminar = new javax.swing.JButton();
        producto_btn_registrar = new javax.swing.JButton();
        producto_btn_actualizar = new javax.swing.JButton();
        producto_txt_buscar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        producto_tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        empleado_tabbed.setBackground(new java.awt.Color(0, 0, 0));
        empleado_tabbed.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        empleado_tabbed.setForeground(new java.awt.Color(255, 255, 255));
        empleado_tabbed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleado_tabbed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleado_tabbedMouseClicked(evt);
            }
        });

        tbb_empleado.setBackground(new java.awt.Color(124, 99, 111));
        tbb_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbb_empleadoMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(168, 143, 156));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajo-en-equipo64.png"))); // NOI18N
        jLabel12.setToolTipText("");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        empleado_pnl_form.setBackground(new java.awt.Color(168, 143, 156));

        try {
            empleado_txt_rut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rut");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cargo");

        empleado_cbo_nivelAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel de acceso");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        javax.swing.GroupLayout empleado_pnl_formLayout = new javax.swing.GroupLayout(empleado_pnl_form);
        empleado_pnl_form.setLayout(empleado_pnl_formLayout);
        empleado_pnl_formLayout.setHorizontalGroup(
            empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleado_pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empleado_cbo_nivelAcceso, 0, 316, Short.MAX_VALUE)
                    .addComponent(empleado_txt_cargo)
                    .addComponent(empleado_txt_rut)
                    .addComponent(empleado_txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empleado_txt_id))
                .addContainerGap())
        );
        empleado_pnl_formLayout.setVerticalGroup(
            empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empleado_pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_cbo_nivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(168, 143, 156));

        empleado_btn_elliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar25.png"))); // NOI18N
        empleado_btn_elliminar.setText("Eliminar");
        empleado_btn_elliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado_btn_elliminarActionPerformed(evt);
            }
        });

        empleado_btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png"))); // NOI18N
        empleado_btn_registrar.setText("Registar");
        empleado_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado_btn_registrarActionPerformed(evt);
            }
        });

        empleado_btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-actualizar 25.png"))); // NOI18N
        empleado_btn_actualizar.setText("Actualizar");
        empleado_btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleado_btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado_btn_actualizarActionPerformed(evt);
            }
        });

        empleado_txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empleado_txt_buscarKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Buscar por nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empleado_btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empleado_btn_elliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empleado_btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empleado_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado_btn_registrar)
                    .addComponent(empleado_btn_elliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empleado_btn_actualizar)
                    .addComponent(empleado_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(empleado_pnl_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empleado_pnl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        empleado_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        empleado_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                empleado_tblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(empleado_tbl);

        javax.swing.GroupLayout tbb_empleadoLayout = new javax.swing.GroupLayout(tbb_empleado);
        tbb_empleado.setLayout(tbb_empleadoLayout);
        tbb_empleadoLayout.setHorizontalGroup(
            tbb_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbb_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        tbb_empleadoLayout.setVerticalGroup(
            tbb_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        empleado_tabbed.addTab("Empleados", new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png")), tbb_empleado); // NOI18N

        tbb_proveedores.setBackground(new java.awt.Color(124, 99, 111));
        tbb_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbb_proveedoresMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(168, 143, 156));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajo-en-equipo64.png"))); // NOI18N
        jLabel13.setToolTipText("");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        proveedor_pnl_form.setBackground(new java.awt.Color(168, 143, 156));

        try {
            proveedor_txt_rut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rut");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");

        javax.swing.GroupLayout proveedor_pnl_formLayout = new javax.swing.GroupLayout(proveedor_pnl_form);
        proveedor_pnl_form.setLayout(proveedor_pnl_formLayout);
        proveedor_pnl_formLayout.setHorizontalGroup(
            proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedor_pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proveedor_txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(proveedor_txt_rut)
                    .addComponent(proveedor_txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proveedor_txt_id)
                    .addComponent(proveedor_txt_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
        );
        proveedor_pnl_formLayout.setVerticalGroup(
            proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proveedor_pnl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor_txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor_txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor_txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedor_pnl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedor_txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(168, 143, 156));

        proveedor_btn_elliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar25.png"))); // NOI18N
        proveedor_btn_elliminar.setText("Eliminar");
        proveedor_btn_elliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedor_btn_elliminarActionPerformed(evt);
            }
        });

        proveedor_btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png"))); // NOI18N
        proveedor_btn_registrar.setText("Registar");
        proveedor_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedor_btn_registrarActionPerformed(evt);
            }
        });

        proveedor_btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-actualizar 25.png"))); // NOI18N
        proveedor_btn_actualizar.setText("Actualizar");
        proveedor_btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proveedor_btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedor_btn_actualizarActionPerformed(evt);
            }
        });

        proveedor_txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                proveedor_txt_buscarKeyReleased(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(255, 102, 102));
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Buscar por nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proveedor_btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedor_btn_elliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedor_btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedor_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor_btn_registrar)
                    .addComponent(proveedor_btn_elliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proveedor_btn_actualizar)
                    .addComponent(proveedor_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(proveedor_pnl_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(proveedor_pnl_form, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proveedor_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        proveedor_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                proveedor_tblMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(proveedor_tbl);

        javax.swing.GroupLayout tbb_proveedoresLayout = new javax.swing.GroupLayout(tbb_proveedores);
        tbb_proveedores.setLayout(tbb_proveedoresLayout);
        tbb_proveedoresLayout.setHorizontalGroup(
            tbb_proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_proveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbb_proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        tbb_proveedoresLayout.setVerticalGroup(
            tbb_proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_proveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        empleado_tabbed.addTab("Proveedores", new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png")), tbb_proveedores); // NOI18N

        tbb_productos.setBackground(new java.awt.Color(124, 99, 111));
        tbb_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbb_productosMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(168, 143, 156));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajo-en-equipo64.png"))); // NOI18N
        jLabel29.setToolTipText("");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        empleado_pnl_form2.setBackground(new java.awt.Color(168, 143, 156));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nombre");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Cantidad");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Precio");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Descripción");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("ID");

        javax.swing.GroupLayout empleado_pnl_form2Layout = new javax.swing.GroupLayout(empleado_pnl_form2);
        empleado_pnl_form2.setLayout(empleado_pnl_form2Layout);
        empleado_pnl_form2Layout.setHorizontalGroup(
            empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleado_pnl_form2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(producto_txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(producto_txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(producto_txt_id)
                    .addComponent(producto_txt_cantidad)
                    .addComponent(producto_txt_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
        );
        empleado_pnl_form2Layout.setVerticalGroup(
            empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empleado_pnl_form2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producto_txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empleado_pnl_form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empleado_pnl_form2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(producto_txt_descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(168, 143, 156));

        producto_btn_elliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar25.png"))); // NOI18N
        producto_btn_elliminar.setText("Eliminar");
        producto_btn_elliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_btn_elliminarActionPerformed(evt);
            }
        });

        producto_btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png"))); // NOI18N
        producto_btn_registrar.setText("Registar");
        producto_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_btn_registrarActionPerformed(evt);
            }
        });

        producto_btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-actualizar 25.png"))); // NOI18N
        producto_btn_actualizar.setText("Actualizar");
        producto_btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        producto_btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_btn_actualizarActionPerformed(evt);
            }
        });

        producto_txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                producto_txt_buscarKeyReleased(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 102, 102));
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Buscar por nombre");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(producto_btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(producto_btn_elliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(producto_btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(producto_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_btn_registrar)
                    .addComponent(producto_btn_elliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(producto_btn_actualizar)
                    .addComponent(producto_txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(empleado_pnl_form2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empleado_pnl_form2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        producto_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        producto_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                producto_tblMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(producto_tbl);

        javax.swing.GroupLayout tbb_productosLayout = new javax.swing.GroupLayout(tbb_productos);
        tbb_productos.setLayout(tbb_productosLayout);
        tbb_productosLayout.setHorizontalGroup(
            tbb_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbb_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        tbb_productosLayout.setVerticalGroup(
            tbb_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbb_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        empleado_tabbed.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/img/anadir25.png")), tbb_productos); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empleado_tabbed)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empleado_tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleado_tabbedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleado_tabbedMouseClicked
        if (empleado_tabbed.getSelectedIndex() == 1) {
            try {
                actualizarTablaEmpleados("");
            } catch (SQLException ex) {
                Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_empleado_tabbedMouseClicked

    private void tbb_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbb_empleadoMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            actualizarTablaEmpleados("");
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbb_empleadoMouseClicked

    private void empleado_btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado_btn_actualizarActionPerformed
        Empleado empleado = tomarDatosEmpleado();
        empleado.setId(Integer.parseInt(empleado_txt_id.getText()));
        try {
            manager.getdEmpleados().update(empleado);
            actualizarTablaEmpleados("");
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_empleado_btn_actualizarActionPerformed

    private void empleado_btn_elliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado_btn_elliminarActionPerformed
        Empleado empleado = new Empleado(Integer.parseInt(empleado_txt_id.getText()));
        try {
            manager.getdEmpleados().delete(empleado);
            actualizarTablaEmpleados("");
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_empleado_btn_elliminarActionPerformed

    private void empleado_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado_btn_registrarActionPerformed
        Empleado empleado = tomarDatosEmpleado();
        try {
            manager.getdEmpleados().create(empleado);
            actualizarTablaEmpleados("");
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_empleado_btn_registrarActionPerformed

    private void empleado_txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleado_txt_buscarKeyReleased
        try {
            String filtro = empleado_txt_buscar.getText();
            actualizarTablaEmpleados(filtro);
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_empleado_txt_buscarKeyReleased

    private void empleado_tblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleado_tblMouseReleased
        int index = empleado_tbl.getSelectedRow();
        empleado_txt_id.setText(empleado_tbl.getValueAt(index, 0).toString());
        empleado_txt_nombre.setText((String) empleado_tbl.getValueAt(index, 1));
        empleado_txt_rut.setText((String) empleado_tbl.getValueAt(index, 2));
        empleado_txt_cargo.setText((String) empleado_tbl.getValueAt(index, 3));
        empleado_cbo_nivelAcceso.setSelectedItem(empleado_tbl.getValueAt(index, 4));
        
    }//GEN-LAST:event_empleado_tblMouseReleased

    private void proveedor_btn_elliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedor_btn_elliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_btn_elliminarActionPerformed

    private void proveedor_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedor_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_btn_registrarActionPerformed

    private void proveedor_btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedor_btn_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_btn_actualizarActionPerformed

    private void proveedor_txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proveedor_txt_buscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_txt_buscarKeyReleased

    private void proveedor_tblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedor_tblMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_tblMouseReleased

    private void tbb_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbb_proveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbb_proveedoresMouseClicked

    private void producto_btn_elliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_btn_elliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_btn_elliminarActionPerformed

    private void producto_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_btn_registrarActionPerformed

    private void producto_btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_btn_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_btn_actualizarActionPerformed

    private void producto_txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_producto_txt_buscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_txt_buscarKeyReleased

    private void producto_tblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producto_tblMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_tblMouseReleased

    private void tbb_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbb_productosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbb_productosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MantenedorAdministrador().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empleado_btn_actualizar;
    private javax.swing.JButton empleado_btn_elliminar;
    private javax.swing.JButton empleado_btn_registrar;
    private javax.swing.JComboBox<String> empleado_cbo_nivelAcceso;
    private javax.swing.JPanel empleado_pnl_form;
    private javax.swing.JPanel empleado_pnl_form2;
    private javax.swing.JTabbedPane empleado_tabbed;
    private javax.swing.JTable empleado_tbl;
    private javax.swing.JTextField empleado_txt_buscar;
    private javax.swing.JTextField empleado_txt_cargo;
    private javax.swing.JTextField empleado_txt_id;
    private javax.swing.JTextField empleado_txt_nombre;
    private javax.swing.JFormattedTextField empleado_txt_rut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton producto_btn_actualizar;
    private javax.swing.JButton producto_btn_elliminar;
    private javax.swing.JButton producto_btn_registrar;
    private javax.swing.JTable producto_tbl;
    private javax.swing.JTextField producto_txt_buscar;
    private javax.swing.JTextField producto_txt_cantidad;
    private javax.swing.JTextField producto_txt_descripcion;
    private javax.swing.JTextField producto_txt_id;
    private javax.swing.JTextField producto_txt_nombre;
    private javax.swing.JTextField producto_txt_precio;
    private javax.swing.JButton proveedor_btn_actualizar;
    private javax.swing.JButton proveedor_btn_elliminar;
    private javax.swing.JButton proveedor_btn_registrar;
    private javax.swing.JPanel proveedor_pnl_form;
    private javax.swing.JTable proveedor_tbl;
    private javax.swing.JTextField proveedor_txt_buscar;
    private javax.swing.JTextField proveedor_txt_correo;
    private javax.swing.JTextField proveedor_txt_id;
    private javax.swing.JTextField proveedor_txt_nombre;
    private javax.swing.JFormattedTextField proveedor_txt_rut;
    private javax.swing.JTextField proveedor_txt_telefono;
    private javax.swing.JPanel tbb_empleado;
    private javax.swing.JPanel tbb_productos;
    private javax.swing.JPanel tbb_proveedores;
    // End of variables declaration//GEN-END:variables

    public void actualizarTablaEmpleados(String filtro) throws SQLException {
        DAOEmpleados daoEmpleado = manager.getdEmpleados();
        List<Empleado> lista = new ArrayList<>();
        if (filtro == "") {
            lista = daoEmpleado.getAll();
            System.out.println(lista);
        } else {
            lista = daoEmpleado.getAll(filtro);
        }

        TMEmpleado model = new TMEmpleado(lista);
        empleado_tbl.setModel(model);
        empleado_tbl.getColumnModel().getColumn(4).setPreferredWidth(desiredWidth);
    }

    public void actualizarTablaProducto() throws SQLException {
        DAOProductos dao = manager.getdProductos();
        List<Producto> lista = dao.getAll();
        TMProducto tmProducto = new TMProducto(lista);
        //tblProductos.setModel(tmProducto);
        //tblProductos.getColumnModel().getColumn(4).setPreferredWidth(desiredWidth);
    }

    public void actualizarTablaProveedores() throws SQLException {
        DAOProveedores dao = manager.getdProveedores();
        List<Proveedor> listaProv = dao.getAll();
        TMProveedore tmProveedores = new TMProveedore(listaProv);
        //tblProveedores.setModel(tmProveedores);
        //tblProveedores.getColumnModel().getColumn(3).setPreferredWidth(desiredWidth);
    }

    /*public void actualizarComboboxProductos() throws SQLException {
        cboProveedorProductos.removeAllItems();
        List<String> nombres;
        nombres = manager.getdProveedores().getNombreProveedor();
        for (String nombre : nombres) {
            //System.out.println(nombre);
            cboProveedorProductos.addItem(nombre);
        }
    }*/

    private Empleado tomarDatosEmpleado() {
        Empleado empleado = new Empleado();
        if (empleado_txt_id.equals("")) {
            empleado.setId(Integer.parseInt(empleado_txt_id.getText()));
        }
        empleado.setNombre(empleado_txt_nombre.getText());
        empleado.setRut(empleado_txt_rut.getText());
        empleado.setCargo(empleado_txt_cargo.getText());
        empleado.setNivelAcceso(Integer.parseInt(empleado_cbo_nivelAcceso.getSelectedItem().toString()));
        System.out.println(empleado);
        return empleado;
    }

    /*public Producto tomarDatosProductos() {
        Producto producto = new Producto();
        producto.setId(Integer.parseInt(txtIdProducto.getText()));
        producto.setNombre(txtNombreProducto.getText());
        producto.setCantidad(Integer.parseInt(txtCantidadProducto.getText()));
        String dato = cboProveedorProductos.getSelectedItem().toString();
        try {
            Proveedor prov = manager.getdProveedores().getOneId(dato);
            producto.setProveedor(prov);
        } catch (SQLException ex) {
            Logger.getLogger(MantenedorAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        producto.setPrecio(Integer.parseInt(txtPrecioProductos.getText()));
        producto.setDescripcion(txtDescripcionProductos.getText());
        return producto;
    }

    private Proveedor tomarDatosProveedor() {
        Proveedor proveedor = new Proveedor();
        proveedor.setNombre(txtNombreProveedor.getText());
        proveedor.setRut(txtRutProveedor.getText());
        proveedor.setCorreo(txtCorreoProveedor.getText());
        proveedor.setTelefono(txtTelefonoProveedor.getText());
        return proveedor;
    }*/

}
